

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "150m"
    max-file: "3"

services:
  redis-stack:
    image: redis/redis-stack:6.2.6-v19
    container_name: redis-stack
    hostname: redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - sip-redis
      - sip-shared
    environment:
      REDIS_ARGS: --include /usr/local/etc/redis/redis.conf
    volumes:
      - sip_redis_stack_data:/data
      - sip_redis_stack_logs:/var/log/redis
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./config/users.acl:/usr/local/etc/redis/users.acl
    logging: *default-logging

networks:
  sip-redis:
    driver: bridge
  sip-shared:
    external: true

volumes:
  sip_redis_stack_data:
  sip_redis_stack_logs:
