

services:
  postgres:
    image: tms-postgres-img
    container_name: tms-postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - tms-bridge
    ports:
      - "5532:5432"
    volumes:
      - tms-pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=tms-db-dev
      - POSTGRES_USER=elanza48
      - POSTGRES_PASSWORD=elanza48
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:6.8
    container_name: tms-pgadmin4
    restart: unless-stopped
    networks:
      - tms-bridge
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: elanza48@postgres.com
      PGADMIN_DEFAULT_PASSWORD: elanza48

volumes:
  tms-pgdata:
  tms-grafana:

networks:
  aip-postgres-stack:
    driver: bridge
  aip-shared:
    external: true